all:
	$(MAKE) -C vol-0
	$(MAKE) -C vol-1
	$(MAKE) -C vol-2
	$(MAKE) -C vol-3
	$(MAKE) -C vol-4
	$(MAKE) -C vol-5
	$(MAKE) -C vol-6
	$(MAKE) -C vol-7
	$(MAKE) -C vol-8
	$(MAKE) -C vol-9
	$(MAKE) -C vol-10

