all:
	$(MAKE) -C etc
	$(MAKE) -C vol-0
	$(MAKE) -C vol-1
	$(MAKE) -C vol-2
acsdoc:
	$(MAKE) -C vol-0 acsdoc
	$(MAKE) -C vol-1 acsdoc
	$(MAKE) -C vol-2 acsdoc
clean:
	$(MAKE) -C vol-0 clean
	$(MAKE) -C vol-1 clean
	$(MAKE) -C vol-2 clean
