all:
	$(MAKE) -C etc
	$(MAKE) -C vol-0
	$(MAKE) -C vol-1
	$(MAKE) -C vol-2
acsdoc:
	$(MAKE) -C vol-0 acsdoc
	$(MAKE) -C vol-1 acsdoc
	$(MAKE) -C vol-2 acsdoc
acscode:
	$(MAKE) -C vol-0 acscode
	$(MAKE) -C vol-1 acscode
	$(MAKE) -C vol-2 acscode
clean:
	$(MAKE) -C vol-0 clean
	$(MAKE) -C vol-1 clean
	$(MAKE) -C vol-2 clean
cleandoc:
	$(MAKE) -C vol-0 cleandoc
	$(MAKE) -C vol-1 cleandoc
	$(MAKE) -C vol-2 cleandoc
