all:
	$(MAKE) -C etc
	$(MAKE) -C msa all
	$(MAKE) -C meta all
acsdoc:
	$(MAKE) -C msa acsdoc
	$(MAKE) -C meta acsdoc
clean:
	$(MAKE) -C msa clean
	$(MAKE) -C meta clean
cleandoc:
	$(MAKE) -C msa cleandoc
	$(MAKE) -C meta cleandoc
acscode:
	$(MAKE) -C msa acscode
	$(MAKE) -C meta acscode

