SRC =  title.ok pref.ok  ch01.ok  ch02.ok  ch03.ok  ch04.ok \
       ch05.ok  ch06.ok  ch07.ok  ch08.ok  ch09.ok  ch10.ok \
       ch11.ok  ch12.ok	 ch13.ok  ch14.ok  ch15.ok  ch16.ok \
       ch17.ok  ch18.ok  ch19.ok  ch20.ok  ch21.ok  ch22.ok \
       ch23.ok  litt.ok

TARGET = volume1

include ../etc/Makefile.inc
