SRC =  title.ok pref.ok  ch01.ok  ch02.ok  ch03.ok  ch04.ok \
       ch05.ok  ch06.ok  ch07.ok  ch08.ok  ch09.ok  ch10.ok litt.ok

SCRIPTSRCS = check_and_install.rb acsstart.cshrc acsresetlibrary.rb

LIBSRCS = acsrequire.rb acs.rb

TARGET = code_management

include ../etc/Makefile.inc
