SRC =  title.ok pref.ok  ch01.ok  ch02.ok  ch03.ok  ch04.ok \
       ch05.ok  ch06.ok  ch07.ok  ch08.ok  ch09.ok  litt.ok
# ch10.ok 

TARGET = volume17

include ../etc/Makefile.inc

# Walter Dehnen's spiffed up version (faster, and more accurate potential):

nbody_sh1 : nbody_sh1WD.C
	g++ -O -o nbody_sh1 nbody_sh1WD.C
