SRC =  title.ok pref.ok  ch01.ok  ch02.ok  ch03.ok  ch04.ok ch05.ok \
       ch06.ok  ch07.ok  ch08.ok  ch09.ok  ch10.ok ch11.ok ch12.ok litt.ok

LOCALSCRIPTSRCS = mkplummer.rb

TARGET = volume9

include ../etc/Makefile.inc
