all:
	$(MAKE) -C vol-0
	$(MAKE) -C vol-1a
	$(MAKE) -C vol-1b
	$(MAKE) -C vol-2
	$(MAKE) -C vol-3
	$(MAKE) -C vol-4
	$(MAKE) -C vol-5
	$(MAKE) -C vol-6
	$(MAKE) -C vol-7
	$(MAKE) -C vol-8
	$(MAKE) -C vol-9
	$(MAKE) -C vol-10
	$(MAKE) -C vol-11
	$(MAKE) -C vol-12
	$(MAKE) -C vol-13
	$(MAKE) -C vol-14
	$(MAKE) -C vol-15
	$(MAKE) -C vol-16

clean:
	$(MAKE) -C vol-0 clean
	$(MAKE) -C vol-1a clean
	$(MAKE) -C vol-1b clean
	$(MAKE) -C vol-2 clean
	$(MAKE) -C vol-3 clean
	$(MAKE) -C vol-4 clean
	$(MAKE) -C vol-5 clean
	$(MAKE) -C vol-6 clean
	$(MAKE) -C vol-7 clean
	$(MAKE) -C vol-8 clean
	$(MAKE) -C vol-9 clean
	$(MAKE) -C vol-10 clean
	$(MAKE) -C vol-11 clean
	$(MAKE) -C vol-12 clean
	$(MAKE) -C vol-13 clean
	$(MAKE) -C vol-14 clean
	$(MAKE) -C vol-15 clean
	$(MAKE) -C vol-16 clean
