all:
	$(MAKE) -C acs_data_format
	$(MAKE) -C binary_trees
	$(MAKE) -C black_hole_trees
	$(MAKE) -C block_symmetric
	$(MAKE) -C code_management
	$(MAKE) -C command_line
	$(MAKE) -C command_line_b
	$(MAKE) -C documentation
	$(MAKE) -C graphics
	$(MAKE) -C indiv_timesteps_1
	$(MAKE) -C indiv_timesteps_2
	$(MAKE) -C indiv_timesteps_3
	$(MAKE) -C lab_assistant
	$(MAKE) -C lab_tools
	$(MAKE) -C multiple_runs
	$(MAKE) -C n_body_problem
	$(MAKE) -C plummer
	$(MAKE) -C polytropes
	$(MAKE) -C shared_timesteps
	$(MAKE) -C speedup
	$(MAKE) -C two_body_problem_1
	$(MAKE) -C two_body_problem_2
	$(MAKE) -C runge_kutta
	$(MAKE) -C symmetric_timesteps
	$(MAKE) -C symplectic
	$(MAKE) -C treecode
	$(MAKE) -C vision
	$(MAKE) -C visualization
acsdoc:
	$(MAKE) -C acs_data_format acsdoc
	$(MAKE) -C binary_trees acsdoc
	$(MAKE) -C black_hole_trees acsdoc
	$(MAKE) -C block_symmetric acsdoc
	$(MAKE) -C code_management acsdoc
	$(MAKE) -C command_line acsdoc
	$(MAKE) -C command_line_b acsdoc
	$(MAKE) -C documentation acsdoc
	$(MAKE) -C graphics acsdoc
	$(MAKE) -C indiv_timesteps_1 acsdoc
	$(MAKE) -C indiv_timesteps_2 acsdoc
	$(MAKE) -C indiv_timesteps_3 acsdoc
	$(MAKE) -C lab_assistant acsdoc
	$(MAKE) -C lab_tools acsdoc
	$(MAKE) -C multiple_runs acsdoc
	$(MAKE) -C n_body_problem acsdoc
	$(MAKE) -C plummer acsdoc
	$(MAKE) -C polytropes acsdoc
	$(MAKE) -C shared_timesteps acsdoc
	$(MAKE) -C speedup acsdoc
	$(MAKE) -C two_body_problem_1 acsdoc
	$(MAKE) -C two_body_problem_2 acsdoc
	$(MAKE) -C runge_kutta acsdoc
	$(MAKE) -C symmetric_timesteps acsdoc
	$(MAKE) -C symplectic acsdoc
	$(MAKE) -C treecode acsdoc
	$(MAKE) -C vision acsdoc
	$(MAKE) -C visualization acsdoc
clean:
	$(MAKE) -C acs_data_format clean
	$(MAKE) -C binary_trees clean
	$(MAKE) -C black_hole_trees clean
	$(MAKE) -C block_symmetric clean
	$(MAKE) -C code_management clean
	$(MAKE) -C command_line clean
	$(MAKE) -C command_line_b clean
	$(MAKE) -C documentation clean
	$(MAKE) -C graphics clean
	$(MAKE) -C indiv_timesteps_1 clean
	$(MAKE) -C indiv_timesteps_2 clean
	$(MAKE) -C indiv_timesteps_3 clean
	$(MAKE) -C lab_assistant clean
	$(MAKE) -C lab_tools clean
	$(MAKE) -C multiple_runs clean
	$(MAKE) -C n_body_problem clean
	$(MAKE) -C plummer clean
	$(MAKE) -C polytropes clean
	$(MAKE) -C shared_timesteps clean
	$(MAKE) -C speedup clean
	$(MAKE) -C two_body_problem_1 clean
	$(MAKE) -C two_body_problem_2 clean
	$(MAKE) -C runge_kutta clean
	$(MAKE) -C symmetric_timesteps clean
	$(MAKE) -C symplectic clean
	$(MAKE) -C treecode clean
	$(MAKE) -C vision clean
	$(MAKE) -C visualization clean
cleandoc:
	$(MAKE) -C acs_data_format cleandoc
	$(MAKE) -C binary_trees cleandoc
	$(MAKE) -C black_hole_trees cleandoc
	$(MAKE) -C block_symmetric cleandoc
	$(MAKE) -C code_management cleandoc
	$(MAKE) -C command_line cleandoc
	$(MAKE) -C command_line_b cleandoc
	$(MAKE) -C documentation cleandoc
	$(MAKE) -C graphics cleandoc
	$(MAKE) -C indiv_timesteps_1 cleandoc
	$(MAKE) -C indiv_timesteps_2 cleandoc
	$(MAKE) -C indiv_timesteps_3 cleandoc
	$(MAKE) -C lab_assistant cleandoc
	$(MAKE) -C lab_tools cleandoc
	$(MAKE) -C multiple_runs cleandoc
	$(MAKE) -C n_body_problem cleandoc
	$(MAKE) -C plummer cleandoc
	$(MAKE) -C polytropes cleandoc
	$(MAKE) -C shared_timesteps cleandoc
	$(MAKE) -C speedup cleandoc
	$(MAKE) -C two_body_problem_1 cleandoc
	$(MAKE) -C two_body_problem_2 cleandoc
	$(MAKE) -C runge_kutta cleandoc
	$(MAKE) -C symmetric_timesteps cleandoc
	$(MAKE) -C symplectic cleandoc
	$(MAKE) -C treecode cleandoc
	$(MAKE) -C vision cleandoc
	$(MAKE) -C visualization cleandoc
acscode:
	$(MAKE) -C acs_data_format acscode
	$(MAKE) -C binary_trees acscode
	$(MAKE) -C black_hole_trees acscode
	$(MAKE) -C block_symmetric acscode
	$(MAKE) -C code_management acscode
	$(MAKE) -C command_line acscode
	$(MAKE) -C command_line_b acscode
	$(MAKE) -C documentation acscode
	$(MAKE) -C graphics acscode
	$(MAKE) -C indiv_timesteps_1 acscode
	$(MAKE) -C indiv_timesteps_2 acscode
	$(MAKE) -C indiv_timesteps_3 acscode
	$(MAKE) -C lab_assistant acscode
	$(MAKE) -C lab_tools acscode
	$(MAKE) -C n_body_problem acscode
	$(MAKE) -C plummer acscode
	$(MAKE) -C polytropes acscode
	$(MAKE) -C shared_timesteps acscode
	$(MAKE) -C speedup acscode
	$(MAKE) -C two_body_problem_1 acscode
	$(MAKE) -C two_body_problem_2 acscode
	$(MAKE) -C runge_kutta acscode
	$(MAKE) -C symmetric_timesteps acscode
	$(MAKE) -C symplectic acscode
	$(MAKE) -C treecode acscode
	$(MAKE) -C vision acscode
	$(MAKE) -C visualization acscode
