SRC =  title.ok pref.ok  ch01.ok  ch02.ok  ch03.ok  ch04.ok \
       ch05.ok  ch06.ok  ch07.ok  ch08.ok  ch09.ok  ch10.ok litt.ok

LOCALSCRIPTSRCS = nbody_cst1.rb nbody_sh1.rb nbody_set_id.rb nbody_diff.rb

TARGET = volume10

include ../etc/Makefile.inc
